# Generated by Django 2.0.7 on 2018-08-03 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_time', models.DateTimeField(verbose_name='报警时间')),
                ('alarm_locate', models.CharField(max_length=20, verbose_name='报警位置信息')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=25, unique=True, verbose_name='公交车ID')),
                ('bus_license_plate', models.CharField(max_length=25, verbose_name='公交车牌号')),
                ('bus_line', models.CharField(blank=True, max_length=25, null=True, verbose_name='公交线路号')),
                ('bus_state', models.BooleanField(choices=[(True, '正常'), (False, '报警')], default=False, verbose_name='公交车状态')),
                ('bus_locate', models.CharField(blank=True, max_length=20, null=True, verbose_name='公交车位置')),
            ],
        ),
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveSmallIntegerField(unique=True, verbose_name='公交公司ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='公司名称')),
                ('company_server', models.CharField(blank=True, max_length=25, null=True, verbose_name='公司服务器地址')),
                ('company_report_list', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='服务器列表')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_create_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusCompany', verbose_name='公交公司ID'),
        ),
        migrations.AddField(
            model_name='bus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alarm',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_bus', to='bus.Bus', verbose_name='公交车ID'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms_create_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
