# Generated by Django 2.0.7 on 2018-08-03 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusCompany',
            new_name='Company',
        ),
    ]
