# Generated by Django 2.0.7 on 2018-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20180803_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.AddField(
            model_name='alarm',
            name='create_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='bus',
            name='create_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='bus',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='create_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='company',
            name='create_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人ID'),
        ),
    ]
